server:
  port: 11412
spring:
  datasource:
    username: driveindex
    url: jdbc:h2:file:./data/logging
    driver-class-name: org.h2.Driver
  sql:
    init:
      schema-locations: classpath:/db/schema.sql
#      data-locations: classpath:/db/data.sql
      mode: always