server:
  port: 11423
spring:
  datasource:
    username: driveindex
    url: jdbc:h2:file:./data/admin
    driver-class-name: org.h2.Driver
  sql:
    init:
      schema-locations: classpath:/db/schema.sql
      data-locations: classpath:/db/data.sql
      mode: always
  h2:
    console:
      enabled: true